### ISSUE TITLE
Misspecified YAML output

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/govdown#1]
I tried knitting the Rmd template provided with the package.

`Error: 'govuk_document' is not an exported object from 'namespace:govdown'`.

It's because `output: govdown::govuk_document` in the YAML should be `output: govdown::govdown_document`.

**Comment by nacnudus** [comment]
Thanks.  I believe this has been fixed in 68442b10efb8e5769b3cc444ac0f48589d218164.
