### ISSUE TITLE
Error: Pandoc options not recognised

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/govdown#2]
Once #1 was fixed in the template, knitting errored in the following way:

```
pandoc: unrecognized option `--lua-filter'
unrecognized option `--resource-path'
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
Execution halted
```

Possibly a version issue?

```
> pandoc_version()
[1] ‘1.19.2.1’
```

**Comment by nacnudus** [comment]
Yes, you need >=2.0.  5939ae7146eaed7d741939b751d3886e690b7840 adds a check.

**Comment by TomFranklin** [comment]
I found this code quite useful in updating a pandoc version FYI @matt-dray @nacnudus https://stackoverflow.com/questions/53788391/installrinstall-pandoc-appears-broken
