### ISSUE TITLE
Add function to make text colouring easier

### ISSUE THREAD

**Issue by mattkerlogue** [ukgovdatascience/govdown#29]
I was thinking it might be good to provide a function that can colour text. `kableExtra::text_spec` can do this, but thought a simple wrapper that combines that and the `govstyle::gov_colours` palette would make it easier (and less cumbersome) to do in-line text colouring.

So:
```
Hello, this is some `r kableExtra::text_spec("red", colour = govstyle::gov_colours['mellow_red'])` text.
```

Becomes:
```
Hello this is some `r govtext("red", "mellow_red")` text.
```

**Comment by mattkerlogue** [comment]
I've written the function below, which checks if you're using a name in the govstyle::gov_cols palette, then in the standard R colours, then an HTML hex code. Passes the text, the colour and additional arguments to `text_spec`.

Will clone and create a PR as and when I get time - presume I need to install the design system stuff to 
edit.

```
govtext <- function(text, colour, ...) {
  
  if (colour %in% names(govstyle::gov_cols)) {
    kbl_colour <- govstyle::gov_cols[colour]
  } else if (colour %in% grDevices::colours()) {
    kbl_colour <- paste0(c("rgb(", paste0(grDevices::col2rgb("wheat1"), collapse = ","), ")"), collapse = "")
  } else if (grepl("^#[A-Fa-f0-9]{6,8}$",colour)) {
    kbl_colour <- colour
  } else {
    stop("Colour supplied [", colour, "] is neither a govstyle::gov_cols colour,
         a standard R colour, or a valid HMTL hexadecimal colour")
  }
  
  kbl_text <- kableExtra::text_spec(x = text, color = kbl_colour, ...)
  
  return(kbl_text)
  
}
```

**Comment by matt-dray** [comment]
Is coloured text allowed? [The Design System](https://design-system.service.gov.uk/styles/colour/) has two text colours and four link colours only.

**Comment by mattkerlogue** [comment]
Hmmm - good point.

The main reason was so that I could make the warning text on this [page](https://mattkerlogue.github.io/coding-guide/workflow.html) stand out a bit more, but I don't want it to have as much emphasis as it being in bold. And it being in colour isn't essential.

From the design system I guess it's [warning text](https://design-system.service.gov.uk/components/warning-text/), [error summary](https://design-system.service.gov.uk/components/error-summary/) or [panel](https://design-system.service.gov.uk/components/panel/). The last two are also probably too much emphasis.

**Comment by nacnudus** [comment]
To implement warning text, I would suggest a lua filter so that

```md
::: {.warning}
Fee fi fo fum
:::
```

Would become the warning text.  Something like this, inserted at line 242 https://github.com/ukgovdatascience/govdown/blob/8b42eac65e641bad69e2bf74832112e7ff7bc5fe/inst/rmarkdown/resources/govuk.lua#L242

```lua
      -- Look for 'warning'
      v,i = el.classes:find("warning")
      if i ~= nil then
        el.classes[i] = nil

        local html
        local res = List:new{}

        html =
          '<div class="govuk-warning-text">' ..
          '<span class="govuk-warning-text__icon" aria-hidden="true">!</span>' ..
          '<strong class="govuk-warning-text__text">'..
          '<span class="govuk-warning-text__assistive">Warning</span>'

        table.insert(res, pandoc.RawBlock('html', html))

        for _, block in ipairs(el.content) do
          table.insert(res, block)
        end

        table.insert(res, pandoc.RawBlock('html', '</strong>'))
        table.insert(res, pandoc.RawBlock('html', '</div>'))

        return res
      end
```

**Comment by mattkerlogue** [comment]
Closing as #30 resolves principal reason for having coloured text.
