### ISSUE TITLE
Text in right-aligned table columns renders in serif font

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/govdown#31]
# Problem

For me, right-aligned columns appear as serif font, but table font should be sans-serif regardless of alignment. I noticed this when looking at the [{govdown} guidance page](https://ukgovdatascience.github.io/govdown/).

# Example

Screenshot from the [{govdown} guidance page](https://ukgovdatascience.github.io/govdown/) rendered in Chrome. The right-aligned column called 'Right' contains serif fonts. Remaining columns are sans-serif.

<img width="979" alt="Screen Shot 2019-06-05 at 16 31 47" src="https://user-images.githubusercontent.com/18232097/58969333-73014380-87af-11e9-912f-0d11a2643a51.png">

The screenshot below is from a locally-knitted govdown Rmd showing that it doesn't matter where the right-aligned column is.

<img width="984" alt="Screen Shot 2019-06-05 at 16 34 28" src="https://user-images.githubusercontent.com/18232097/58969613-e7d47d80-87af-11e9-989e-2df85ab01066.png">

# Reproducibility

This occurs for me regardless of browser (Chrome, Safari and Firefox) on my work Mac. I've also reproduced it locally by knitting a govdown Rmd containing tables produced in 
markdown format and when using `knitr::kable()`.

Wasn't a problem in @nacnudus's setup, I believe.

# Potential cause

Misbehaviour of `govuk-table__cell--numeric`? Inspection in browser implies sans-serif font though.

<img width="1597" alt="Screen Shot 2019-06-05 at 12 00 16" src="https://user-images.githubusercontent.com/18232097/58969699-0c305a00-87b0-11e9-8d31-fa202d55e49d.png">

**Comment by nacnudus** [comment]
Confirmed. Thanks for the detailed the report.
