### ISSUE TITLE
CRAN Release

### ISSUE THREAD

**Issue by nacnudus** [ukgovdatascience/govdown#34]
For use by teams that can only install from CRAN, not GitHub.

`usethis::use_release_issue()`

**Comment by yihui** [comment]
When I first saw this package name, I thought someone implemented a joke I told [in my talk](https://resources.rstudio.com/rstudio-conf-2019/pagedown-creating-beautiful-pdfs-with-r-markdown-and-css) at rstudio::conf 2019. 😂 Upon a closer look, I'm so amazed and impressed by your Pandoc and web skills (in particular, the Pandoc lua filters are so neat!). Nice job! Thanks for the great package!

**Comment by nacnudus** [comment]
Wow thank you @yihui!  Perhaps if we have our own government shutdown I'll have time to implement it in blogdown too.

**Comment by nacnudus** [comment]
CRAN release 83c4a69aff56ff3e0926713ebce92954af4aec74
