### ISSUE TITLE
New Transport rendering

### ISSUE THREAD

**Issue by mattkerlogue** [ukgovdatascience/govdown#38]
Docs with `font: "sans-serif"` are rendering pages with New Transport. 

``` r
---
output:
  govdown::govdown_document:
    font: "sans-serif" 
---

# Test

```

Results in:

![Screen Shot 2019-09-18 at 13 00 23](https://user-images.githubusercontent.com/35345053/65146689-51516280-da14-11e9-8806-8c6fe5b3a485.png)

See also govdown [main page](https://ukgovdatascience.github.io/govdown/) despite [_site.yml](https://github.com/ukgovdatascience/govdown/blob/master/_site.yml) specifying `sans-serif`.

![Screen Shot 2019-09-18 at 13 03 02](https://user-images.githubusercontent.com/35345053/65146855-b86f1700-da14-11e9-9eb9-85ba7d7db23b.png)

**Comment by mattkerlogue** [comment]
Just looked at the page source for the test doc and govdown index, they both include references to “GDS Transport” in style blocks. So could either use readLines and scan for a reference to that, or use rvest to inspect it. Looked through the source for my mapping page (rendered in older version) and has no such references.

Could use this as a means for running a testing script.

**Comment by nacnudus** [comment]
Unfortunately even a test that scanned the html for references to the font wouldn't have detected this regression, because they renamed the font.
