### ISSUE TITLE
Pandoc issues with v0.5

### ISSUE THREAD

**Issue by mattkerlogue** [ukgovdatascience/govdown#39]
Encountering some pandoc issues with v0.5:
1. Not respecting the `output_dir: docs` setting in `_site.yml` and rendering the HMTL files in the top-level directory
2. Pandoc hanging - mainly seems to be happening when knitting this [index.Rmd](https://github.com/co-analysis/co-coffee-and-coding) file - which is plain markdown no R code. Also causes a hang when building the whole site as a result.

Have downgraded to v0.4.1 and the Rmd and site build correctly.

**Comment by nacnudus** [comment]
I think this is fixed, just checking that it hasn't regressed a related issue.

**Comment by nacnudus** [comment]
Presumed fixed.
