### ISSUE TITLE
Poor favicon contrast when browser tab is selected

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/govdown#4]
# Chrome

Not selected
![Screen Shot 2019-03-28 at 09 22 39](https://user-images.githubusercontent.com/18232097/55145786-56a3b380-513b-11e9-9487-a8d3952c9a8c.png)

Selected
![Screen Shot 2019-03-28 at 09 22 52](https://user-images.githubusercontent.com/18232097/55145792-57d4e080-513b-11e9-973e-e9432e9b3ef4.png)

# Firefox

Not selected
<img width="220" alt="Screen Shot 2019-03-28 at 09 23 46" src="https://user-images.githubusercontent.com/18232097/55145830-6c18dd80-513b-11e9-839f-0a2ac570021a.png">

Selected
<img width="220" alt="Screen Shot 2019-03-28 at 09 23 51" src="https://user-images.githubusercontent.com/18232097/55145840-6de2a100-513b-11e9-9791-87aa850bd36e.png">

**Comment by nacnudus** [comment]
I'm absolutely stuck on this.  It's something to do with `mask-icon.svg`.  I have tried [this guidance](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html) but can't get it working locally.

**Comment by nacnudus** [comment]
Fixed in 3cd76e62bdcb70cd983d0953a9c0210c3e373a47.  It was nothing to do with `mask-icon.svg` :man_facepalming:
