### ISSUE TITLE
Details not display summary label

### ISSUE THREAD

**Issue by mattkerlogue** [ukgovdatascience/govdown#40]
When I create a details block the summary label doesn't appear. Compare this [Rmd](https://github.com/co-analysis/csmapping/blob/206721bcf62fe67f21097a85bae54998d458e68c/cs_lad_2019.Rmd#L104) with the [html](https://co-analysis.github.io/csmapping/cs_lad_2019.html).

From a brief scan, I think line 45 of `govuk.lua` might not be right and that it should be calling `i.attributes` rather than `el.attributes`

```
pandoc.utils.stringify(el.attributes["summary"]) ..
```

**Comment by nacnudus** [comment]
I can't reproduce the problem.

Has the html been rendered off that version of the Rmd?  It has bullet points that aren't in the Rmd.

**Comment by nacnudus** [comment]
Confirmed. Also on android chrome, where it can't even be opened.

![image](https://user-images.githubusercontent.com/3522552/67313016-2cac4700-f4fa-11e9-8a65-537cf36ee7b2.png)

**Comment by nacnudus** [comment]
Only confirmed on the Travis build.  Maybe it's a bug in `pandoc.utils.stringify()` that has been fixed since version 2.2.1, which is what the default Travis distro seems to use, going by the log:

```sh
curl -fLo /tmp/pandoc-2.2-1-amd64.deb https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-1-amd64.deb
```

**Comment by nacnudus** [comment]
Well this has been fun.  v2.7 works, and so do [v2.6](1c7cb125bf275f8ab49a5cf65ac2c92ed2bceb05) and [v2.5](70a03d3ecc20da5101de5eaf9818bf3aa1629264).  Now what?

* Require v2.5?  But it seems to be hard enough for people to get v2.0.
* Document the "details" component?  People will only see that if they refer to the docs when writing their own page, but not when they inherit a page from someone else.
* Write my own `stringify` :weary: 

@mattkerlogue as the main user, are you able to install pandoc v2.5+?

**Comment by nacnudus** [comment]
Writing my own `stringify` to support old versions of Pandoc looks like a pain and isn't justified at the moment.  Users are welcome to ask for it if they need it though.
