### ISSUE TITLE
GOV.UK Design System support

### ISSUE THREAD

**Issue by NickColley** [ukgovdatascience/govdown#52]
Hello :)

This project is awesome! Thanks for sharing it.

In two places you mention that the Design System doesnt support a few things, have you considered raising an issue on GitHub with what you expected to happen? We may be able to improve the Design System to allow for your use case.

> Bulletted lists work as normal, but nested bullets don’t look very good because they aren’t really supported by the GOV.UK Design System.

> Numbered lists work as normal, except that nested numbered lists don’t work at all because they aren’t supported by the GOV.UK Design System.

You can raise a new issue on GOV.UK Frontend: https://github.com/alphagov/govuk-frontend/issues

Nick

**Comment by nacnudus** [comment]
Thanks Nick!

I meant those paragraphs to sound more deferential to the Design System.  The limitations are a _good_ thing, and we certainly don't have any evidence of a need for nested bullets.  I'll rewrite the docs to reflect that.

**Comment by nacnudus** [comment]
See 38d856bebada64ae185e6387bc100cd7b9daec7f
