### ISSUE TITLE
Implement tables 

### ISSUE THREAD

**Issue by nacnudus** [ukgovdatascience/govdown#8]
https://design-system.service.gov.uk/components/table/

**Comment by TimTaylor** [comment]
Tables seem trickier to implement.  A temporary workaround is to post-process the govdown html output with a function that performs the necessary substitutions.  A somewhat verbose and hacky function (`process_tables`) for this is given at https://gist.github.com/tjtnew/04a5327c8e3653587d45cab747c7c45c.

Consider the following R Markdown file `test.Rmd`:
````
---
title: Table testing
author: Tester
date: March 27, 2019
output:
  govdown::govdown_document:
  font: "sans-serif"
---

Testing the implementation

```{r}
my_table <- data.frame(month = c("January", "February", "March", "April"),
                       rating = c("good", "very good", "good", "bad"),
                       number = c(1, 2, 3, 4),
                       outcome = c("pass", "fail", "pass", "fail"))
knitr::kable(my_table, caption = "Test table")
```
````
This can the be rendered first by calling rmarkdown and then passing the output to `process_tables`
```
rmarkdown::render("test.Rmd")
process_tables("test.html", "tabled_test.html")
```

**Comment by nacnudus** [comment]
I've committed a long-winded lua implementation, but it's late on Friday so I'm bound to have messed up something.
